title: The Art of Developers
author: Barun Thapa
email: barunthapa.bvdt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  being the hawkeye

# social links
twitter_username: barunthapabvdt
github_username:  barunthapa

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
